### PR TITLE
Upgrade Geant4 to 10.4.3

### PR DESCRIPTION
**Pull request by gipert**
Because of a nasty bug, see mppmu/MaGe#187

@oschulz could you also push the new container to the Docker hub? Thanks

### CODE REVIEW

**Comment by gipert** [comment]
I would also add some tags to version the container (on the Docker hub as well). I was thinking about something like this, based on our usage for MaGe simulations:
- `2f7e4b9` -> `v1.2.0`
- `4e2564e` -> `v1.2.1`
- `a743b54` -> `v1.3.0`

**Comment by gipert** [comment]
`ping` @oschulz

**Comment by gipert** [comment]
Hi @oschulz, I am reviewing the GERDA container status and making everything available for people to build our containers in the future. Can I ask you to update the gerda-base images on the Docker hub? My proposal is to the remove the `legacy` image there (I really don't know where that comes from) and use version tags associated to this repo. I would then tag the following commits here:
```
git tag 96e713f v1.0.0 # GEANT4 9
git tag 2f7e4b9 v1.2.0 # GEANT4 10
git tag 4e2564e v1.2.1
git tag 6b88c8e v1.3.0 # GEANT4 10.4.3, also `latest` on DockerHub
```
(GEANT4/CLHEP versions are almost the only changing thing here) and keep the corresponding Docker containers on the DockerHub for MaGe. Would you be so kind to push the images?

Thanks a lot.

PS: Are there gerda-sw-all builds on the Docker Hub??? https://hub.docker.com/r/mppmu/gerda-sw-all

**Comment by oschulz** [comment]
> Can I ask you to update the gerda-base images on the Docker hub

**Comment by oschulz** [comment]
> We should implement broadcasting (.+-syntax ) methods for our Point and Vector types.

Sure, will do!

> Are there gerda-sw-all builds on the Docker Hub

Hm, that was supposed to be non-public, I think. I removed it.

**Comment by oschulz** [comment]
> My proposal is to the remove the legacy image there

I think Anna needed that for a while.

>  I would then tag the following commits here

Why not tag the commits first, before I build?

**Comment by oschulz** [comment]
> Why not tag the commits first, before I build?

Hm, maybe I better build first, in case there's trouble ...

**Comment by gipert** [comment]
> Why not tag the commits first, before I build

As you like :) Everything should build fine though, I already did that on my machine

Thanks a lot!

**Comment by oschulz** [comment]
I can't build them, the geant4 download paths seems to be broken or temporarily down (e.g. https://geant4.web.cern.ch/support/source/geant4.9.6.p04.tar.gz)

**Comment by gipert** [comment]
Dammit, looks like they changed all URLs. This (e.g.) works now: https://geant4-data.web.cern.ch/releases/geant4.9.6.p04.tar.gz . Could you change them manually?

**Comment by oschulz** [comment]
We can change it in "provisioning/install-sw-scripts/geant4-setup.sh", but we'll have to rebase all commits we wanted to tag on top of it.

**Comment by gipert** [comment]
What a pain, I'll do that.

**Comment by gipert** [comment]
Hi Oliver, I rebased and re-tagged everything in my fork: https://github.com/gipert/mppmu_gerda-base_img/tree/dev could you check that you can build the containers now? If yes you'll need to force-push to master...

**Comment by oschulz** [comment]
Will build - but are you sure about these version numbers? We were already at v7.0.0 ... going back to v1.x.y doesn't seem right.

**Comment by gipert** [comment]
This is for the gerda-base container, not gerda-sw-all...

**Comment by oschulz** [comment]
Ah, silly me!

**Comment by oschulz** [comment]
v1.0.0 still seems to be part of the current master branch tree, though?

**Comment by gipert** [comment]
Yep, that's the only tag which was already there. But now that I rebased everything the tag's commit hash is different...

**Comment by oschulz** [comment]
Anyhow, I see the corresponding commit on your rebased branch ... starting the build now.

**Comment by oschulz** [comment]
Ok, all done I hope - I force-pushed master to your commit  b1fada3. The docker images are build and pushed to dockerhub: https://hub.docker.com/repository/docker/mppmu/gerda-base .

Can you check if all is correct?

**Comment by oschulz** [comment]
I also changed tag v1.0.0 to the new tree.

**Comment by gipert** [comment]
Thank you so much Oli! I'll make some tests and let you know if there's something wrong

**Pull request merged**
